### ISSUE TITLE
Error function name

### ISSUE THREAD

**Issue by laozhizi** [nightw/mikoomi-zabbix-mongodb-monitoring#10]
write_to_log_file(line 82) should be write_to_data_lines.

**Comment by nightw** [comment]
@laozhizi You're right in the sense that there is no `write_to_log_file` function is present anymore, so it breaks for sure. That's a bug. But I think that it should be `write_to_log` instead of `write_to_data_lines`, since it's a debug message and it's not in the format which the Zabbix server could process (since the content of the `$data_lines` array is sent to the Zabbix server directly).

If you agree with my suggestion then could you please send a simple pull request with the fix?

**Comment by nightw** [comment]
@laozhizi I've made a quick fix in commit 64a8aad. Please test it out. I close this issue now, but if anything is wrong with the fix, then feel free to reopen it.
