### ISSUE TITLE
Invalid XML tag "/zabbix_export": unexpected tag "time".

### ISSUE THREAD

**Issue by pratapsingh** [nightw/mikoomi-zabbix-mongodb-monitoring#17]
Hi ,

I am trying to import the template but getting below error:

**Invalid XML tag "/zabbix_export": unexpected tag "time".**

Zabix Version : **Zabbix 3.0.1**

I see that on URL https://github.com/nightw/mikoomi-zabbix-mongodb-monitoring/issues/9 it is referred as closed but I am getting this issue. Can someone let me know if there is any changes to be made in template file?

**Comment by nightw** [comment]
@pratapsingh You should try to import the template from the directory `mongodb-2.4` not from the root of the project. If that works, then please let me know and I will update the documentation about this to be less confusing. Thanks.

**Comment by 4admin2root** [comment]
I have the same issue.

it works with mongodb-2.4/MongoDB_Plugin_template_export-24.xml

thank you @nightw

**Comment by corysmith-bydeluxe** [comment]
Is it recommended to use the 2.4 template with the 3.2 scripts?  If there is more functionality in the 3.2 scripts, let me know and I'll try to fix the template to match.

**Comment by nightw** [comment]
@corysmith-bydeluxe In theory there is no additional functionality in the newer version of the check, only changed some key names (also they're changed in the newer version of the template, so they should match). But if you find anything missing or could add any more functionality then you're very welcome to do so. Thank you for the offer.

In general The 2.4 versions of the template should be used with Zabbix 3.0 and above. To make this whole thing a bit more straightforward I've moved the old template to the `-2.2` directory and copied the new template to the `-3.2` directory from the `2.4` one to have it in both places to make sure it gets used by default by anybody who stumbles upon this repository without even reading the documentation.

I'm closing this issue, since it was just a misunderstanding/documentation issue, which is fixed now.

**Comment by pratapsingh** [comment]
@nightw  Thanks that worked
